#! /bin/sh
#launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
#config monitors
xrandr --output HDMI1 --primary --mode 1920x1080  &
~/.config/polybar/launch.sh &
picom --experimental-backends &
feh --bg-fill  ~/walls/gho.png &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          40

bspc config top_padding		30
bspc config bottom_padding	30
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc rule -a Firefox desktop='II'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


